// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFv-KAV9SQSeaJZaESehaKwYZ81VferaI',
    appId: '1:253020141090:web:c3c8c66882836db7297c7b',
    messagingSenderId: '253020141090',
    projectId: 'microzaimich',
    authDomain: 'microzaimich.firebaseapp.com',
    storageBucket: 'microzaimich.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBP5AOWT1RgEUvTa_OgVoRxbLQMLvTYw84',
    appId: '1:253020141090:android:58e80aa52566d89f297c7b',
    messagingSenderId: '253020141090',
    projectId: 'microzaimich',
    storageBucket: 'microzaimich.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1VJiZaH7osDQkwq07ZKjmzLWe465cbR4',
    appId: '1:253020141090:ios:89cec17458c510cd297c7b',
    messagingSenderId: '253020141090',
    projectId: 'microzaimich',
    storageBucket: 'microzaimich.firebasestorage.app',
    iosBundleId: 'com.example.microzaimich',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1VJiZaH7osDQkwq07ZKjmzLWe465cbR4',
    appId: '1:253020141090:ios:89cec17458c510cd297c7b',
    messagingSenderId: '253020141090',
    projectId: 'microzaimich',
    storageBucket: 'microzaimich.firebasestorage.app',
    iosBundleId: 'com.example.microzaimich',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFv-KAV9SQSeaJZaESehaKwYZ81VferaI',
    appId: '1:253020141090:web:0f83d9ce39178263297c7b',
    messagingSenderId: '253020141090',
    projectId: 'microzaimich',
    authDomain: 'microzaimich.firebaseapp.com',
    storageBucket: 'microzaimich.firebasestorage.app',
  );
}
